version: '3.4'

services:
  primoapi:
    container_name: primoapi
    image: primoapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes: 
      - ./primoapi:/primoapi
